[package]
name = "rox-lang"
version = "0.0.0"
license = "MIT AND Apache-2.0"
description = "The Rox Programming Language"
authors = ["Reese Williams <reese@reesew.io>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/reese/rox"
homepage = "https://github.com/reese/rox"
categories = ["command-line-utilities"]
keywords = ["compiler", "programming language", "rox"]

[lib]
name = "rox"
path = "src/lib.rs"

[[bin]]
name = "rox"
path = "src/bin/rox.rs"

[build-dependencies]
lalrpop = { version = "0.18.1", features = ["lexer"] }

[dependencies]
im = "14.3.0"
lalrpop-util = "0.18.1"
regex = "1"

[dev-dependencies]
rusty-hook = "^0.10.3"
