[package]
name = "rox"
version = "0.0.1"
authors = ["Reese Williams <rtwill722@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.7"
matches = "*"
num-traits = "*"
num-derive = "*"

[dev-dependencies]
yotsuba = "*"
